"""initial_migration_with_uuid

Revision ID: fcbf6c2fcc92
Revises: 
Create Date: 2026-01-31 08:05:37.208706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcbf6c2fcc92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop existing tables if they exist (in reverse dependency order)
    connection = op.get_bind()
    tables_to_drop = [
        'affiliate_commissions', 'trades', 'payments', 'affiliate_referrals',
        'affiliate_payouts', 'wallets', 'telegram_connections', 'subscriptions',
        'notifications', 'affiliates', 'users', 'signals', 'email_templates'
    ]
    for table in tables_to_drop:
        connection.execute(sa.text(f'DROP TABLE IF EXISTS {table} CASCADE'))

    # Drop existing enum types if they exist
    enum_types = [
        'signaldirection', 'signalstatus', 'signaloutcome', 'tradedirection',
        'tradestatus', 'tradeclosereason', 'wallettype', 'walletstatus',
        'subscriptionplan', 'subscriptionstatus', 'paymentstatus', 'payoutstatus',
        'notificationtype', 'notificationchannel'
    ]
    for enum_type in enum_types:
        connection.execute(sa.text(f'DROP TYPE IF EXISTS {enum_type} CASCADE'))

    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='signaldirection'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXECUTED', 'EXPIRED', 'CANCELLED', name='signalstatus'), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'TP_HIT', 'SL_HIT', 'MANUAL_CLOSE', 'EXPIRED', name='signaloutcome'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('suggested_leverage', sa.Integer(), nullable=False),
    sa.Column('suggested_position_size_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('consensus_votes', sa.Integer(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_price_at_creation', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('actual_exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('actual_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=500), nullable=True),
    sa.Column('password_reset_token', sa.String(length=500), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('affiliates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('active_referrals', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pending_earnings', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('paid_earnings', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('payout_address', sa.String(length=255), nullable=True),
    sa.Column('payout_currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_affiliates_id'), 'affiliates', ['id'], unique=False)
    op.create_index(op.f('ix_affiliates_referral_code'), 'affiliates', ['referral_code'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('SIGNAL', 'TRADE_OPENED', 'TRADE_CLOSED', 'TP_HIT', 'SL_HIT', 'SUBSCRIPTION', 'PAYMENT', 'SYSTEM', 'AFFILIATE', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'BOTH', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('telegram_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('MONTHLY', 'YEARLY', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'GRACE_PERIOD', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_crypto', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('crypto_currency', sa.String(length=10), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('renewal_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('telegram_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_code', sa.String(length=20), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('signal_notifications', sa.Boolean(), nullable=False),
    sa.Column('trade_notifications', sa.Boolean(), nullable=False),
    sa.Column('system_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_telegram_connections_id'), 'telegram_connections', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('wallet_type', sa.Enum('MASTER', 'API', name='wallettype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DISCONNECTED', 'SUSPENDED', name='walletstatus'), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=True),
    sa.Column('is_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('authorization_signature', sa.Text(), nullable=True),
    sa.Column('balance_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('affiliate_payouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_payouts_affiliate_id'), 'affiliate_payouts', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_payouts_id'), 'affiliate_payouts', ['id'], unique=False)
    op.create_table('affiliate_referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=False),
    sa.Column('referred_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    op.create_index(op.f('ix_affiliate_referrals_affiliate_id'), 'affiliate_referrals', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_referrals_id'), 'affiliate_referrals', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('nowpayments_id', sa.String(length=100), nullable=True),
    sa.Column('nowpayments_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'CONFIRMING', 'CONFIRMED', 'SENDING', 'PARTIALLY_PAID', 'FINISHED', 'FAILED', 'REFUNDED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('actually_paid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pay_currency', sa.String(length=10), nullable=True),
    sa.Column('pay_address', sa.String(length=255), nullable=True),
    sa.Column('payin_hash', sa.String(length=255), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nowpayments_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPENING', 'OPEN', 'CLOSING', 'CLOSED', 'FAILED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('position_size_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fees_paid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('funding_paid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close_reason', sa.Enum('TP_HIT', 'SL_HIT', 'MANUAL', 'LIQUIDATION', 'SIGNAL_EXPIRED', 'SYSTEM', name='tradeclosereason'), nullable=True),
    sa.Column('hyperliquid_order_id', sa.String(length=100), nullable=True),
    sa.Column('hyperliquid_position_id', sa.String(length=100), nullable=True),
    sa.Column('order_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_index(op.f('ix_trades_wallet_id'), 'trades', ['wallet_id'], unique=False)
    op.create_table('affiliate_commissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_id'], ['affiliate_referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_commissions_affiliate_id'), 'affiliate_commissions', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_id'), 'affiliate_commissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_commissions_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_affiliate_id'), table_name='affiliate_commissions')
    op.drop_table('affiliate_commissions')
    op.drop_index(op.f('ix_trades_wallet_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_affiliate_referrals_id'), table_name='affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_referrals_affiliate_id'), table_name='affiliate_referrals')
    op.drop_table('affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_payouts_id'), table_name='affiliate_payouts')
    op.drop_index(op.f('ix_affiliate_payouts_affiliate_id'), table_name='affiliate_payouts')
    op.drop_table('affiliate_payouts')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_telegram_connections_id'), table_name='telegram_connections')
    op.drop_table('telegram_connections')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_affiliates_referral_code'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_id'), table_name='affiliates')
    op.drop_table('affiliates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
